# sample automation file which uses all features available today
timezone: pacific

devices:
  - name: Dining Room_Left Window
    type: shade
    location_tags: ["Living_Room"]
  - name: Dining Room_Right Window
    type: shade
    location_tags: ["Living_Room"]
  - name: Master Bedroom_Left Shade
    type: shade
    location_tags: ["Bed_Room"]
  - name: Master Bedroom_Center Window
    type: shade
    location_tags: ["Bed_Room"]
  - name: Master Bedroom_Right Window
    type: shade
    location_tags: ["Bed_Room"]
  - name: Electric_Switch_1
    type: switch

automations:
  - name: Morning_Bedroom_Partial
    schedule:
      cron: "30 7 * * *"
    devices:
      device_list:
        - name: Master Bedroom_Left Shade
          value: 34
        - name: Master Bedroom_Center Window
          value: 34
        - name: Master Bedroom_Right Window
          value: 10
  - name: Morning_Bedroom_Full
    schedule: 
      cron: "10 8 * * *"
    devices:
      tags: ["Bed_Room"]
    setting: open
  - name: Morning_Living_Room
    schedule: 
      cron: "0 9 * * *"
    devices:
      tags: ["Living_Room"]
    setting: 66
  - name: Summer_Evening_Living_Room
    schedule: 
      cron: "15 17 * 3,4,5,6,7,8,9 *"
    devices:
      tags: ["Living_Room"]
    setting: open
  - name: Evening_All_Close
    schedule:
      cron: "0 15 * * *"
      sunset:
        hours: 1
    devices:
      tags: ["Living_Room", "Bed_Room"]
    setting: closed
        
